# -*- coding: utf-8 -*-
"""HotPotQA_BM25_Standalone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/aaryaupi/hotpotqa-bm25-standalone.aae7376b-9bfd-48a7-9ae4-349efabbce01.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260525/auto/storage/goog4_request%26X-Goog-Date%3D20260525T011038Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Db858e01ed801e0e74dfd29c4a5e89f9bb01482e33717f5702503f9b1cb14d11b6308b202f812282a936ce1f329cb33b73c86bc05dc2e22af502ba07607e9d0df60045c4e7711c276817bd838467fe044f4e2811b928a13d0f7ff650008ff196e9dc63ce8e7d8b11307512182cb88698da4dcf8e0245d2bff6d1dc27b99f91f7d957b0faf5c03f3b9cc6191a28bfff0836774ce30246398762da6096692e49a19ede4da0aa92e6cb78129da2012373832f47313393aaf550b9e3cdca72e610e41da20e8d536b4e45b2b741cc2410d2c19ecd0f8c63cece1193367b2dc4e1b68e922d718d0f41b0ae3f1e2d9d7059ba88c387bc15915536668d7333774eb332788
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
jeromeblanchet_hotpotqa_question_answering_dataset_path = kagglehub.dataset_download('jeromeblanchet/hotpotqa-question-answering-dataset')

print('Data source import complete.')

#!pip install rank-bm25 -q

#!pip install rank_bm25 langsmith -q
#!python -m spacy download en_core_web_sm -q

# The code is completly Modified for T4 4 CORE CPU and might require refactor for other CPU set
# if ran on the worng CPU config there is a overflow error that is unresolved by me so be carefull 

import json
import time
import spacy
import numpy as np
from tqdm import tqdm
from datasets import load_dataset
from rank_bm25 import BM25Okapi
from langsmith import traceable, Client
import os
nlp = spacy.load("en_core_web_sm")

from datasets import load_dataset

def load_hotpotqa():
    # distractor — this is the right choice
    ds = load_dataset("hotpotqa/hotpot_qa", "distractor")

    train = ds["train"]       # 90,447
    dev   = ds["validation"]  # 7,405

    print(f"Train: {len(train)}  Dev: {len(dev)}")
    return train, dev

train_ds, dev_ds = load_hotpotqa()

# What one record looks like after loading
sample = dev_ds[0]
print("Question:",   sample["question"])
print("Answer:",     sample["answer"])
print("Type:",       sample["type"])    # "bridge" or "comparison"
print("Level:",      sample["level"])   # "easy", "medium", "hard"
print("Gold titles", sample["supporting_facts"]["title"])
print("Context titles:", sample["context"]["title"])   # 10 titles
print("Num passages:",   len(sample["context"]["title"]))  # always 10

# Each record has context["title"] and context["sentences"]
# These are PARALLEL arrays — title[i] matches sentences[i]

def extract_passages_from_record(record: dict) -> list[dict]:
    """
    Extract the 10 candidate passages for this question.
    Each passage = all sentences for that title joined.
    """
    passages = []
    titles    = record["context"]["title"]
    sentences = record["context"]["sentences"]
    gold_titles = set(record["supporting_facts"]["title"])

    for title, sents in zip(titles, sentences):
        passages.append({
            "title":    title,
            "text":     " ".join(sents),
            "is_gold":  title in gold_titles,  # True for 2, False for 8
        })

    return passages

# Sample output for one record:
# [
#   {title: "Eiffel Tower",   text: "...", is_gold: False},  # distractor
#   {title: "Roland Garros",  text: "...", is_gold: True},   # gold
#   {title: "Paris",          text: "...", is_gold: False},  # distractor
#   {title: "Novak Djokovic", text: "...", is_gold: True},   # gold
#   ... 6 more distractors
# ]

# HotpotQA has two question types
# "bridge" — needs bridge entity reasoning  ← YOUR USE CASE
# "comparison" — needs comparing two entities (who is older, etc.)

# For your pipeline, bridge questions are the target
# Comparison questions are a different failure mode

bridge_dev = [r for r in dev_ds if r["type"] == "bridge"]
comp_dev   = [r for r in dev_ds if r["type"] == "comparison"]

print(f"Bridge:     {len(bridge_dev)}")   # ~5,600
print(f"Comparison: {len(comp_dev)}")     # ~1,800

# Start with bridge only
# Your Agent B chain reasoning is built for bridge
# Comparison needs a different agent strategy
# Add comparison in week 2 if time allows

OUTPUT_DIR       = "/kaggle/working"
BASELINE_PATH    = f"{OUTPUT_DIR}/bm25_baseline_results.json"
HARD_FAIL_PATH   = f"{OUTPUT_DIR}/hard_failures.json"
CHECKPOINT_PATH  = f"{OUTPUT_DIR}/bm25_checkpoint.json"

def process_record(record: dict) -> dict:
    """
    Runs BM25 over the 10 candidate passages in one record.
    Self-contained — no global state except rank_bm25.
    Safe for multiprocessing.
    """
    import spacy
    from rank_bm25 import BM25Okapi
    import numpy as np

    # Lazy load spaCy per worker — cached after first call in each process
    if not hasattr(process_record, "_nlp"):
        process_record._nlp = spacy.load(
            "en_core_web_sm",
            disable=["parser", "lemmatizer"]  # NER only — faster
        )
    nlp = process_record._nlp

    query       = record["question"]
    titles      = record["context"]["title"]
    sentences   = record["context"]["sentences"]
    gold_titles = set(record["supporting_facts"]["title"])

    # Build 10 passages
    passages = [
        {
            "title":   title,
            "text":    " ".join(sents),
            "is_gold": title in gold_titles,
        }
        for title, sents in zip(titles, sentences)
    ]

    # BM25
    tokenised  = [p["text"].lower().split() for p in passages]
    bm25       = BM25Okapi(tokenised)
    scores     = bm25.get_scores(query.lower().split())
    ranked_idx = scores.argsort()[::-1]
    ranked     = [
        {
            **passages[i],
            "bm25_score": round(float(scores[i]), 4),
            "rank":       int(rank + 1),
        }
        for rank, i in enumerate(ranked_idx)
    ]

    # Metrics
    top1_correct    = ranked[0]["is_gold"]
    first_gold_rank = next((r["rank"] for r in ranked if r["is_gold"]), 11)
    gold_ranks      = [r["rank"] for r in ranked if r["is_gold"]]
    mrr             = round(1.0 / first_gold_rank, 4)

    hits_at_1  = int(any(r["rank"] <= 1  and r["is_gold"] for r in ranked))
    hits_at_3  = int(any(r["rank"] <= 3  and r["is_gold"] for r in ranked))
    hits_at_10 = int(any(r["rank"] <= 10 and r["is_gold"] for r in ranked))

    # nDCG@10
    relevances = [1 if r["is_gold"] else 0 for r in ranked[:10]]
    dcg        = sum(rel / np.log2(i + 2) for i, rel in enumerate(relevances))
    idcg       = sum(1.0 / np.log2(i + 2) for i in range(min(2, 10)))
    ndcg       = round(dcg / idcg, 4) if idcg > 0 else 0.0

    recall_at_10 = round(
        sum(1 for r in ranked[:10] if r["is_gold"]) / max(len(gold_titles), 1),
        4
    )

    # NER for agent context signals
    top1_ents = set(ent.text.lower() for ent in nlp(ranked[0]["text"]).ents)
    gold_text = next((p["text"] for p in passages if p["is_gold"]), "")
    gold_ents = set(ent.text.lower() for ent in nlp(gold_text).ents)
    q_ents    = [ent.text for ent in nlp(query).ents]

    return {
        # Identity
        "id":    record["id"],
        "type":  record["type"],
        "level": record["level"],
        "split": None,          # filled in after map

        # Query
        "query":       query,
        "answer":      record["answer"],
        "gold_titles": list(gold_titles),

        # Ranking
        "ranked_passages": [
            {
                "title":      r["title"],
                "bm25_score": r["bm25_score"],
                "rank":       r["rank"],
                "is_gold":    r["is_gold"],
            }
            for r in ranked
        ],
        "top1_title":      ranked[0]["title"],
        "top1_correct":    top1_correct,
        "first_gold_rank": first_gold_rank,
        "gold_ranks":      gold_ranks,

        # Metrics
        "hits_at_1":    hits_at_1,
        "hits_at_3":    hits_at_3,
        "hits_at_10":   hits_at_10,
        "mrr":          mrr,
        "ndcg_at_10":   ndcg,
        "recall_at_10": recall_at_10,

        # Agent signals
        "only_answer_has":   sorted(gold_ents - top1_ents),
        "only_wrong_has":    sorted(top1_ents - gold_ents),
        "bridge_candidates": q_ents,

        # Full candidate text for agents
        "candidates": [
            {
                "title":      r["title"],
                "text":       r["text"],
                "bm25_score": r["bm25_score"],
                "rank":       r["rank"],
                "is_gold":    r["is_gold"],
            }
            for r in ranked
        ],
    }

def run_bm25_baseline_t4(train_ds, dev_ds):

    all_results = []

    for split_name, split_ds in [("train", train_ds), ("dev", dev_ds)]:
        print(f"\nProcessing {split_name} ({len(split_ds)} records) "
              f"on 4 cores...")
        t0 = time.time()

        # datasets.map handles parallelism, progress bar, and batching
        mapped = split_ds.map(
            process_record,
            num_proc         = 4,       # all T4 CPU cores
            desc             = f"BM25 {split_name}",
            load_from_cache_file  = False,   # always rerun fresh
        )

        # Add split label and convert to list
        results = mapped.to_list()
        for r in results:
            r["split"] = split_name
        all_results.extend(results)

        elapsed = time.time() - t0
        n       = len(split_ds)
        print(f"  {split_name}: {n} records in {elapsed:.1f}s "
              f"({n/elapsed:.0f} rec/s)")

        # Checkpoint after each split
        print(f"  Checkpointing {len(all_results)} results...")
        with open(CHECKPOINT_PATH, "w") as f:
            json.dump(all_results, f)
        print(f"  Checkpoint saved.")

    return all_results

print("\nStarting BM25 baseline on T4...")
t_total    = time.time()
all_results = run_bm25_baseline_t4(train_ds, dev_ds)
print(f"\nTotal time: {(time.time()-t_total)/60:.1f} min")

print("\nSaving outputs...")

with open(BASELINE_PATH, "w") as f:
    json.dump(all_results, f, indent=2)
print(f"bm25_baseline_results.json  — {len(all_results)} records")

hard_failures = [r for r in all_results if not r["top1_correct"]]
with open(HARD_FAIL_PATH, "w") as f:
    json.dump(hard_failures, f, indent=2)
print(f"hard_failures.json          — {len(hard_failures)} records")


def print_metrics(records, label):
    n = len(records)
    if n == 0:
        return
    print(f"\n{'='*50}")
    print(f"  {label}  (n={n})")
    print(f"{'='*50}")
    print(f"  Hits@1:        {sum(r['hits_at_1']   for r in records)/n:.4f}")
    print(f"  Hits@3:        {sum(r['hits_at_3']   for r in records)/n:.4f}")
    print(f"  Hits@10:       {sum(r['hits_at_10']  for r in records)/n:.4f}")
    print(f"  MRR:           {sum(r['mrr']          for r in records)/n:.4f}")
    print(f"  nDCG@10:       {sum(r['ndcg_at_10']   for r in records)/n:.4f}")
    print(f"  Recall@10:     {sum(r['recall_at_10'] for r in records)/n:.4f}")
    fails = sum(1 for r in records if not r["top1_correct"])
    print(f"  Hard failures: {fails}  ({100*fails/n:.1f}%)")

print_metrics(all_results,                                        "FULL DATASET")
print_metrics([r for r in all_results if r["split"] == "train"], "TRAIN")
print_metrics([r for r in all_results if r["split"] == "dev"],   "DEV")
print_metrics([r for r in all_results if r["type"]  == "bridge"],     "BRIDGE")
print_metrics([r for r in all_results if r["type"]  == "comparison"], "COMPARISON")

hf_train  = [r for r in hard_failures if r["split"] == "train"]
hf_dev    = [r for r in hard_failures if r["split"] == "dev"]
hf_bridge = [r for r in hard_failures if r["type"]  == "bridge"]
hf_comp   = [r for r in hard_failures if r["type"]  == "comparison"]

print(f"\n{'='*50}")
print(f"  HARD FAILURES")
print(f"{'='*50}")
print(f"  Total:      {len(hard_failures)}")
print(f"  Train:      {len(hf_train)}")
print(f"  Dev:        {len(hf_dev)}")
print(f"  Bridge:     {len(hf_bridge)}")
print(f"  Comparison: {len(hf_comp)}")
for level in ["easy", "medium", "hard"]:
    n = sum(1 for r in hard_failures if r["level"] == level)
    print(f"  {level}:     {n}")

print(f"\nDone. Files in {OUTPUT_DIR}")